### PR TITLE
Add hyperbolic ops

### LINKED ISSUE #612: hyperbolic functions missing
I may be wrong, but I couldn't find native functions for cosh and sinh.
Of course one could always rewrite the definitions using exponential function, but having a ops.sinh or ops.cosh would be a nice addition.

### PR DESCRIPTION
**Pull request by FayazRahman**
- Adds hyperbolic ops to ops/numpy
- Closes #612

### CODE REVIEW

**Review by fchollet — APPROVED** [review]
Thanks for the contribution! Looking good 👍

**Comment by fchollet** [comment]
Please check out the test failures -- to format the code you can use `sh shell/format.sh`

**Comment by FayazRahman** [comment]
Pushed fixes. Just noticed there is a `tanh` in `ops.nn` as well, I'm wondering if we needs to be done about that.

**Comment by fchollet** [comment]
> Just noticed there is a tanh in ops.nn as well, I'm wondering if something needs to be done about that.

Typically it will be accessed from `ops`. I think we should remove the one from `ops.nn` and keep the `numpy` one.

**Review by fchollet — APPROVED** [review]
Thank you! 👍

**Comment by fchollet** [comment]
Still seems to be some test failures.

**Comment by FayazRahman** [comment]
Those tests are passing for me on all backends though.

**Pull request merged**
