### PR TITLE
Export DTypePolicy as Policy for backward compat

### PR DESCRIPTION
**Pull request by abheesht17**
Resolves https://github.com/keras-team/keras-core/issues/468

### CODE REVIEW

**Comment by abheesht17** [comment]
Does `@keras_core_export` not work as expected? Had to add an extra statement in `__init__.py`. There are other such cases in the repo. For example,

https://github.com/keras-team/keras-core/blob/d85be712db84b2c030a4e79a217c8066f08f08b1/keras_core/backend/config.py#L35-L37

```
>>> import keras_core as keras
Using TensorFlow backend
>>> keras.config.set_floatx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keras_core' has no attribute 'config'
```

**Comment by mattdangerw** [comment]
Two reasons you might be seeing `'keras_core' has no attribute 'config'`...

1) you did a `pip install .` or `pip install repo_url` instead of using `python pip_build.py --install`
2) you are running a script from the base of the keras-core repo, in which case the local directory `keras_core` will take precedence over the installed version.

**Comment by abheesht17** [comment]
Ah, yes. You are right. The second reason is why it's happening

**Review by fchollet — APPROVED** [review]
LGTM, thanks

**Pull request merged**
