### PR TITLE
Add `irfft` and `istft`

### PR DESCRIPTION
**Pull request by james77777778**
Similar to #717 
This PR mainly implements `istft`. This allows us to reconstruct sequences from the frequency domain.

Notes: some clean up (e.g. `a` to `x`, `jax.numpy` to `jnp`) included, I can revert it if it is not necessary

```bash
# output
# lr means librosa's output
# needs `center=True` to get reasonable result
ori. vs. lr RMSE: 3.663534e-09
ori. vs. np RMSE: 4.223074e-09
ori. vs. jax RMSE: 8.257622e-09
ori. vs. tf RMSE: 1.0522875e-08
ori. vs. torch RMSE: 8.910108e-09
```

Reconstructed results:
output

A standalone script:
(needs `pip install librosa matplotlib`)

```python
import jax
import librosa as lr
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

from keras_core.backend.jax.math import istft as jax_istft
from keras_core.backend.numpy.math import istft as np_istft
from keras_core.backend.tensorflow.math import istft as tf_istft
from keras_core.backend.torch.math import istft as torch_istft

# load waveform from librosa
waveform, samplerate = lr.load(lr.util.example("trumpet"))
waveform = waveform.astype(np.float32)
n = len(waveform)

# produce stft output from librosa with random parameters
sequence_length = 234
sequence_stride = 123
fft_length = 567
length = n
center = True

lr_stfts = lr.core.stft(
    waveform,
    hop_length=sequence_stride,
    win_length=sequence_length,
    n_fft=fft_length,
    center=center,
)
lr_stfts = np.transpose(lr_stfts)
real_out, imag_out = np.real(lr_stfts), np.imag(lr_stfts)

# reference istft output from librosa
lr_out = lr.core.istft(
    np.transpose(lr_stfts),
    hop_length=sequence_stride,
    win_length=sequence_length,
    n_fft=fft_length,
    length=length,
    center=center,
)
lr_rmse = np.sqrt(np.mean((lr_out - waveform) ** 2))
print("ori. vs. lr RMSE:", lr_rmse)

# compute istft with keras-core
arguments = {
    "sequence_length": sequence_length,
    "sequence_stride": sequence_stride,
    "fft_length": fft_length,
    "length": length,
    "center": center,
}
np_out = np_istft((real_out, imag_out), **arguments)
tf_out = tf.function(tf_istft, jit_compile=True)(
    (real_out, imag_out), **arguments
).numpy()
torch_out = torch_istft((real_out, imag_out), **arguments).numpy()
jax_out = jax.jit(lambda x: jax_istft(x, **arguments))((real_out, imag_out))
jax_out = np.array(jax_out)

# RMSE between all backends and librosa
np_rmse = np.sqrt(np.mean((np_out - waveform) ** 2))
print("ori. vs. np RMSE:", np_rmse)
jax_rmse = np.sqrt(np.mean((jax_out - waveform) ** 2))
print("ori. vs. jax RMSE:", jax_rmse)
tf_rmse = np.sqrt(np.mean((tf_out - waveform) ** 2))
print("ori. vs. tf RMSE:", tf_rmse)
torch_rmse = np.sqrt(np.mean((torch_out - waveform) ** 2))
print("ori. vs. torch RMSE:", torch_rmse)

# visaulization
fig, ax_dict = plt.subplot_mosaic(
    [["A", "LR", "B", "C", "D", "E"]], figsize=(30, 6)
)
ax_dict["A"].set_title("Original Waveform")
ax_dict["A"].plot(waveform)
ax_dict["LR"].set_title("Librosa")
ax_dict["LR"].plot(lr_out)
ax_dict["B"].set_title("NumPy")
ax_dict["B"].plot(np_out)
ax_dict["C"].set_title("JAX")
ax_dict["C"].plot(jax_out)
ax_dict["D"].set_title("TensorFlow")
ax_dict["D"].plot(tf_out)
ax_dict["E"].set_title("Torch")
ax_dict["E"].plot(torch_out)
plt.tight_layout()
plt.savefig("output.png")

```

### CODE REVIEW

**Comment by fchollet** [comment]
Thanks for the PR!

You are implementing `irfft` using the built-in implementation in TF, JAX, torch and numpy, but not `istft`. However, `istft` also has a built-in implementation in TF, JAX (`jax.scipy`), torch, and scipy (but not numpy). Can we use that instead (since it would be simpler)?

Meanwhile, `overlap_sequences` doesn't seem to be a standard API -- why do we need it?

**Comment by james77777778** [comment]
> However, `istft` also has a built-in implementation in TF, JAX (`jax.scipy`), torch, and scipy (but not numpy). Can we use that instead (since it would be simpler)?

After a tons of trial and error, I have managed to implement `stft` and `istft` as the following table:

Goal: make `stft` and `istft` have the almost same output compared to `librosa`

|backend|stft|istft|note|
|-|-|-|-|
|numpy|`scipy.signal.stft`|custom implementation|I can't make `scipy.signal.istft` match the librosa's output|
|jax|`jax.scipy.signal.stft`|custom implementation|the reason is the same as numpy|
|tf|`tf.signal.stft`|`tf.signal.inverse_stft`||
|torch|`torch.stft`|custom implementation|`torch.istft` is buggy and I failed to match the librosa's output|

ref:
- runtime error of `torch.istft`: https://github.com/pytorch/pytorch/issues/91309

> Meanwhile, `overlap_sequences` doesn't seem to be a standard API -- why do we need it?

I have removed it.
Now, `_overlap_sequences` is only used in the `backend.*.math`.

**Comment by james77777778** [comment]
@fchollet 

The reconstruction error in numpy and jax has increased after the new implementation, but it should be still acceptable.

```bash
# from the standalone script
# lastest implementation
ori. vs. lr RMSE: 3.663534e-09
ori. vs. np RMSE: 9.218377e-09  <= before: 4.223074e-09
ori. vs. jax RMSE: 9.20385e-09  <= before: 8.257622e-09
ori. vs. tf RMSE: 1.0522875e-08
ori. vs. torch RMSE: 8.910108e-09
```

**Comment by fchollet** [comment]
In general anything in the vicinity of float32 precision is perfectly acceptable.

**Review by fchollet — APPROVED** [review]
LGTM, thank you for the contribution! It is certainly more concise this way.

**Pull request merged**
